package-lock.json
package.json

Use latest commons

---

package-lock.json
package.json

Use fixed httptransfer
Fixes failing binary upload when multipart

Use fixed httptransfer

---

package-lock.json
package.json

update commons dep

---

package-lock.json
package.json

release draft: https://github.com/adobe/asset-compute-sdk/releases/tag/untagged-4e2887a8e04b25e06806

manual release: 2.2.0

---

.releaserc
.travis.yml
package-lock.json
package.json

Was surprisingly missing from sdk.

add semantic-release setup

---

README.md
lib/rendition.js
lib/storage.js
lib/worker.js
package-lock.json
package.json
test/api.test.js
test/rendition.test.js
test/storage.test.js

- based of POC in PR: https://github.com/adobe/asset-compute-sdk/pull/12
- default behavior is opt-out of embedded renditions
- to opt-in, you must set the `embedBinaryLimit` on the rendition object:
```js
{
source: "https://example.com/MySourceFile.jpg"
renditions: [{
fmt: "png",
embedBinaryLimit: 32 * 1024 // 32 kb is the max value
}]
}
```
- io event `rendition_created` will store the rendition as a Data Uri in the `data` field of the event:
```js
{
type: "rendition_created",
rendition: {
fmt: "png",
embedBinaryLimit: embedBinaryLimit
},
data: 'data:application/octet-stream;base64,aGVsbG8gd29ybGQ=',
source: "https://example.com/MySourceFile.jpg"
}
```
Notes:
- if you specify an `embedBinaryLimit` that is greater than our max limit (32kb), it will not embed the rendition (this is …

FEATURE-RELEASE: Embed small renditions in io events

---

README.md

[NUI-696](https://jira.corp.adobe.com/browse/NUI-696) doc review
Replaces internal documentation links with external one.

replace adobe corp GitHub links

---

lib/worker.js

Fixes timers (I think - except if there are other issues? But I didn't see more of them).
Fixes # https://jira.corp.adobe.com/browse/NUI-688

More updates

---

lib/rendition.js
lib/worker.js
package-lock.json
test/rendition.postprocess.test.js

honestly, the timers are really a mess... it was a struggle to just get the timers correct without refactoring.
The issue is in batchWorker, we don't really have a `currentCallbackProcessing` and a `currentPostProcessing` because they happen in batch. But also, we technically do have a `currentPostProcessing` since we post-process one by one. So it leaves a weird position, in rendition metrics for batch workers, the `callbackProcessDuration` metric is equal to the total callbackProcessDuration for all the renditions. So following this, it would make the most sense to make the `postProcessDuration` metric for each rendition the total `postProcessDuration`....an easy way to do this would be simply setting the `this.timers.currentPostProcessing` timer equal to the …

fix timers

---

README.md

1. document the post processing changes in the readme
- I didn't document all details of the instructions such as `jpegSize` yet, would take too long, we can refine later
2. use this PR to release a new version of the sdk via `FEATURE-RELEASE`

NUI-668 documentation

---

lib/storage.js
package-lock.json

use rename instead of copy for asset compute cli test worker post processing 
Fixes # https://jira.corp.adobe.com/browse/NUI-824

NUI-824 use rename instead of copy

---

lib/postprocessing/image.js
lib/postprocessing/math.js
lib/storage.js
test/math.test.js
test/source.test.js
test/storage.test.js

might have been overkill but got math.js to 100% code coverage...I guess I like math too much lol
Fixes # https://jira.corp.adobe.com/browse/NUI-842

math and storage unit tests for watermarking

---

lib/utils/type.js

It is very confusing to log the entire error stack. Especially when investigating for actual errors, this is misleading
```
[rendition 0] file command failed: { Error: Command failed: file -b --mime "/nodejsAction/dXjaYqoD/work/42615341dd8642dba15341dd8692db59/out/rendition0.transfer"
/bin/sh: 1: file: not found
at ChildProcess.exithandler (child_process.js:294:12)
at ChildProcess.emit (events.js:198:13)
at maybeClose (internal/child_process.js:982:16)
at Socket.stream.socket.on (internal/child_process.js:389:11)
at Socket.emit (events.js:198:13)
at Pipe._handle.close (net.js:607:12)
killed: false,
code: 127,
signal: null,
cmd:
'file -b --mime "/nodejsAction/dXjaYqoD/work/42615341dd8642dba15341dd8692db59/out/rendition0.transfer"',
stdout: '',
stderr: '/bin/sh: 1: file: not found\n' } …
```

do not log entire error stack for file cmd

---

package-lock.json
package.json

release v2.9.0: https://github.com/adobe/asset-compute-sdk/releases/tag/v2.9.0
Fixes # https://jira.corp.adobe.com/browse/NUI-915

NUI-915 update package.json version number

---

lib/storage/http.js
lib/worker.js
package-lock.json
package.json
test-worker/manifest.yml
test/storage/http-multipart.test.js

We were seeing a lot of errors without retrying for `worker-transfer` uploads. It was using the default value of 60s for `maxRetryDuration` so if the first upload request took longer than 1 min (which if often did during a large load). The easiest solution was to increase maxRetryDuration to 15 mins.
It is very clear from this unit test & other logs in `worker-transfer` that we do retry on connection errors. 
[example logs](https://adobeiort.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22runtime_prod_ext%22%20activation_id%3D4e8f47863a2749dd8f47863a27b9dde7%20%7C%20sort%20_time%20%7C%20fields%20%2B%20_time%2Clog_message%20%7C%20fields%20-%20_raw%20%7C%20outputtext&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-1d%40d&latest=%40d&display.page.search.showFiel …

NUI-919 retry for longer on multipart uploads

---

test-worker/package.json

release notes: https://github.com/adobe/aio-cli-plugin-asset-compute/releases/tag/v1.4.6
it's a bug fix, so it will get picked up anyways. But it is an important bug fix so it's best to keep this updated
Fixes # none

update aio-cli-plugin-asset-compute version with bug fix

---

package-lock.json
package.json

use new version of node-httptransfer with important bug fix: https://github.com/adobe/node-httptransfer/pull/32
Fixes # https://jira.corp.adobe.com/browse/NUI-1021

NUI-1021 use new version of httptransfer

---

lib/api.js
lib/worker-transformer.js
package-lock.json
package.json
test-worker/package.json
test-worker/worker.js

mob-test passes:
```
Test cases:
- png-png
✔  Succeeded. 2s 476ms (worker 2s 210ms)
✔︎ All tests were successful.
- Tests run      : 1
- Failures       : 0
- Errors         : 0
- ```

Use released pipeline

---

lib/worker-pipeline.js
package-lock.json
package.json

Follow up of cleanup ticket, now that this is done in the pipeline, the SDK no longer needs to move the test file around: https://git.corp.adobe.com/nui/asset-compute-pipeline/pull/17
testing:
```
Test cases:
- png-png
✔  Succeeded. 2s 461ms (worker 2s 227ms)
✔︎ All tests were successful.
- Tests run      : 1
- Failures       : 0
- Errors         : 0
```

follow up of NUI-1220, remove moving files post engine.run

---

package-lock.json
package.json

Retrigger release, as in the title. 
Attempt to get a release for https://github.com/adobe/asset-compute-sdk/pull/132.

Retrigger release

---

.github/workflows/node.js.yml
lib/api.js
lib/postprocessing/image.js
lib/rendition.js
lib/worker-pipeline.js
package-lock.json
package.json
test-worker/package.json
test-worker/worker.js

For https://jira.corp.adobe.com/browse/NUI-1425 : Prepare mob session branches for merge
This PR is to merge into mob-session
- code cleanup and ensure unit tests pass
- rebase with master
- pending 
- update pipeline dependency once open sourced (only will then the GitHub CI will pass)

merge ready mob-session with rebased master

---

.github/workflows/node.js.yml
test-worker/package.json

github action brought in most recent version of aio-cli which is not compatible with our cli plugin:
```
> aio info && adobe-asset-compute test-worker
System:
OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Memory: 3.32 GB / 6.79 GB
Shell: 5.0.17 - /bin/bash
Binaries:
Node: 10.16.3 - /opt/hostedtoolcache/node/10.16.3/x64/bin/node
Yarn: 1.22.10 - /usr/local/bin/yarn
npm: 7.20.2 - ~/work/asset-compute-sdk/asset-compute-sdk/node_modules/.bin/npm
Virtualization:
Docker: 20.10.7+ - /usr/bin/docker
npmGlobalPackages:
@adobe/aio-cli: 8.0.0
CLI plugins:
core:
@adobe/aio-cli 8.0.0
@adobe/aio-cli-plugin-app 8.0.0
@adobe/aio-cli-plugin-auth 2.4.1
@adobe/aio-cli-plugin-certificate 0.3.0
@adobe/aio-cli-plugin-config 2.3.0 …
```

NUI-1502: pin aio v7.1.0 until aio-cli-plugin-asset-compute is backwards compatible

---

package-lock.json
package.json

update pipeline version: https://github.com/adobe/asset-compute-pipeline/releases/tag/v2.0.0 
(it is a bugfix but the version number accidentally got increased a major)

BUGFIX-RELEASE: update asset-compute-pipeline version

---

package-lock.json
package.json

cascading release: https://github.com/adobe/asset-compute-pipeline/pull/10
Fixes # https://jira.corp.adobe.com/browse/NUI-1528

NUI-1528 cascading release, update asset-compute-pipeline version

---

lib/prepare.js
lib/shell/shellscript.js
lib/utils/utils.js
package-lock.json
test/shellscript.test.js

Shell script worker now takes parameters longer than 8000 characters and stores them in a temporary file.  The parameter value is replaced with the path of the temporary file and an environment variable FILE_PARAMS is set with the name(s) of parameters that had this substitution performed.
Fixes CQ-4329896

CQ-4329896 - Added long parameter support with working test

---

lib/worker.js
package-lock.json
package.json

redact credentials when logging the rendition
supporting PR: https://github.com/adobe/asset-compute-commons/pull/62
Fixes # https://jira.corp.adobe.com/browse/NUI-1577

NUI-1577 Redact azure media services credentials for worker-azuremediaservice

---

package-lock.json
package.json

update pipeline version to support datauri rendition in the pipeline

NUI-1462 update pipeline version to support datauri rendition in the pipeline

---

README.md

This PR is created to trigger CI pipeline release for previous merge request. 
The change removes an extra line in README.md

NUI-1462 follow up

---

package-lock.json
package.json

bump pipeline version to 6.0.0 for metadata extraction
Fixes https://jira.corp.adobe.com/browse/NUI-1661

bump pipeline version to 6.0.0

---

package-lock.json
package.json

bump pipeline version to 6.0.1
Fixes/Improve # https://jira.corp.adobe.com/browse/NUI-1661

bump pipeline version to 6.0.1

---

test/webaction.test.js

Fix re-require issues for mock-require.

Fix re-require in unit tests

---

.github/workflows/node.js.yml
package-lock.json
package.json

Normalize mimetypes to make sure they can be understood by other libraries by using pipeline from https://github.com/adobe/asset-compute-pipeline/pull/44.
Fixes #CQ-4339915, [#ASSETS-347](https://jira.corp.adobe.com/browse/ASSETS-347)

[ASSETS-347][CQ-4339915] Use new pipeline

---

.github/workflows/node.js.yml

https://github.com/adobe/asset-compute-sdk/runs/5225177376?check_suite_focus=true

update version used in semantic release

---

package-lock.json
package.json

cascading release: https://github.com/adobe/node-openwhisk-newrelic/pull/56
new module versions included in this PR: 
- https://github.com/adobe/asset-compute-commons/releases/tag/v1.1.7
- https://github.com/adobe/asset-compute-pipeline/releases/tag/v7.2.1
Ticket: https://jira.corp.adobe.com/browse/ASSETS-9702

ASSETS-9702 Cascading release of node-openwhisk-newrelic

---

package-lock.json
package.json

Cascade release for https://jira.corp.adobe.com/browse/ASSETS-20566
Recently IO Events returns 204, because of a cache issue in their infrastructure.

ASSETS-20566 cascade release asset-compute-events-clients

---

package-lock.json
package.json

For https://jira.corp.adobe.com/browse/ASSETS-20895
update asset-compute-pipeline

cascade release pipeline

---

.github/workflows/node.js.yml
package-lock.json
package.json
test/api.test.js

ASSET-30851 update dependencies for commons and pipeline

---

README.md

BUGFIX-RELEASE: Whitespace commit to force version bump
